# Generated by Django 5.2.13 on 2026-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='violation_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
