# Generated by Django 5.2.13 on 2026-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_content_moderation_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentmoderationlog',
            new_name='moderation__target__622763_idx',
            old_name='moderation_content_target_idx',
        ),
        migrations.RenameIndex(
            model_name='contentmoderationlog',
            new_name='moderation__created_139c2f_idx',
            old_name='moderation_content_created_idx',
        ),
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='action',
            field=models.CharField(choices=[('flag', 'Flag'), ('unflag', 'Unflag'), ('hide', 'Hide'), ('restore', 'Restore'), ('delete', 'Delete'), ('update', 'Update'), ('resolve', 'Resolve'), ('reject', 'Reject'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('ignore', 'Ignore'), ('resolved', 'Resolved')], max_length=20),
        ),
    ]
