# Generated by Django 5.2.13 on 2026-05-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_owner'),
        ('moderation', '0002_rename_moderation_content_target_idx_moderation__target__622763_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentmoderationlog',
            new_name='content_mod_target__05658b_idx',
            old_name='moderation__target__622763_idx',
        ),
        migrations.RenameIndex(
            model_name='contentmoderationlog',
            new_name='content_mod_created_cc952c_idx',
            old_name='moderation__created_139c2f_idx',
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='is_automatic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='source',
            field=models.CharField(choices=[('regex', 'Regex'), ('ml', 'Machine Learning'), ('user_report', 'User Report'), ('admin', 'Admin')], default='regex', max_length=20),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contentmoderationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='action',
            field=models.CharField(choices=[('flag', 'Flag'), ('unflag', 'Unflag'), ('hide', 'Hide'), ('restore', 'Restore'), ('delete', 'Delete'), ('update', 'Update'), ('resolve', 'Resolve'), ('reject', 'Reject'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('ignore', 'Ignore'), ('resolved', 'Resolved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='target_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('post_image', 'Post Image'), ('comment_image', 'Comment Image'), ('post_file', 'Post File'), ('comment_file', 'Comment File'), ('hashtag', 'Hashtag')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='contentmoderationlog',
            index=models.Index(fields=['source'], name='content_mod_source_07bf08_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationlog',
            index=models.Index(fields=['status'], name='content_mod_status_8849a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationlog',
            index=models.Index(fields=['risk_score'], name='content_mod_risk_sc_62d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmoderationlog',
            index=models.Index(fields=['actor'], name='content_mod_actor_i_6d6ecd_idx'),
        ),
        migrations.AlterModelTable(
            name='contentmoderationlog',
            table='content_moderation_logs',
        ),
    ]
