# Generated by Django 5.2.13 on 2026-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_rename_moderation__target__622763_idx_content_mod_target__05658b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmoderationlog',
            name='target_type',
            field=models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('post_image', 'Post Image'), ('comment_image', 'Comment Image'), ('post_file', 'Post File'), ('comment_file', 'Comment File'), ('hashtag', 'Hashtag')], max_length=30),
        ),
    ]
