# Generated by Django 5.1.14 on 2026-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="group_covers/"),
        ),
        migrations.AddField(
            model_name="group",
            name="default_sort",
            field=models.CharField(
                choices=[
                    ("latest_activity", "Hoạt động mới nhất"),
                    ("newest", "Bài viết mới"),
                    ("relevant", "Phù hợp nhất"),
                ],
                default="latest_activity",
                help_text="Tiêu chí sắp xếp bài viết mặc định",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="mod_can_approve_edit",
            field=models.BooleanField(
                default=False, help_text="Cho phép Người kiểm duyệt phê duyệt chỉnh sửa"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="mod_can_approve_member",
            field=models.BooleanField(
                default=False,
                help_text="Cho phép Người kiểm duyệt phê duyệt thành viên",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="mod_can_approve_post",
            field=models.BooleanField(
                default=False, help_text="Cho phép Người kiểm duyệt phê duyệt bài viết"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="require_edit_approval",
            field=models.BooleanField(
                default=False, help_text="Bật để yêu cầu phê duyệt khi chỉnh sửa"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="require_post_approval",
            field=models.BooleanField(
                default=False, help_text="Bật để yêu cầu phê duyệt bài viết mới"
            ),
        ),
    ]
