# Generated by Django 5.1.14 on 2026-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_cover_image_group_default_sort_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="mod_can_approve_edit",
        ),
        migrations.RemoveField(
            model_name="group",
            name="mod_can_approve_member",
        ),
        migrations.RemoveField(
            model_name="group",
            name="mod_can_approve_post",
        ),
        migrations.AddField(
            model_name="group",
            name="admin_can_approve_edit",
            field=models.BooleanField(
                default=True, help_text="Cho phép Admin phê duyệt bài viết đã sửa"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="admin_can_approve_member",
            field=models.BooleanField(
                default=True, help_text="Cho phép Admin phê duyệt thành viên"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="admin_can_approve_post",
            field=models.BooleanField(
                default=True, help_text="Cho phép Admin phê duyệt bài viết"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="require_edit_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="group",
            name="require_post_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Chủ sở hữu"),
                    ("admin", "Quản trị viên"),
                    ("member", "Thành viên"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grouprolepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Chủ sở hữu"),
                    ("admin", "Quản trị viên"),
                    ("member", "Thành viên"),
                ],
                max_length=20,
            ),
        ),
    ]
