# Generated by Django 5.2.13 on 2026-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ví dụ: MAX_UPLOAD_MB, ENABLE_REGISTRATION', max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('data_type', models.CharField(choices=[('int', 'Số nguyên (Limit)'), ('bool', 'Bật/Tắt (Toggle)'), ('string', 'Văn bản')], default='string', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
