# Generated by Django 5.2.13 on 2026-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_commentreaction_reaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('flagged', 'Flagged'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('flagged', 'Flagged'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='normal', max_length=20),
        ),
    ]
