# Generated by Django 5.2.13 on 2026-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_status_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
    ]
