# Generated by Django 5.2.10 on 2026-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_notification_is_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='reaction_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb_code',
            field=models.CharField(choices=[('react_post', 'React Post'), ('comment_post', 'Comment Post'), ('share_post', 'Share Post'), ('mention_in_post', 'Mention in Post'), ('react_comment', 'React Comment'), ('reply_comment', 'Reply Comment'), ('mention_in_comment', 'Mention in Comment'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('follow_user', 'Follow User'), ('group_invite', 'Group Invite'), ('group_join_request', 'Group Join Request'), ('group_request_accept', 'Group Request Accept'), ('post_in_group', 'Post in Group'), ('system_alert', 'System Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'),
        ),
    ]
